### ISSUE TITLE
Enable the user to see the current configuration from the UI

### ISSUE THREAD

**Issue by eolivelli** [diennea/carapaceproxy#10]
Add views on the UI to see:
- configured backends (yet done)
- configured listeners (yet done)
- configured routes
- configured actions
- configured directors

A full dump of current configuration

**Comment by Pols95** [comment]
> Add views on the UI to see:
> 
> * configured actions
> * configured backends
> * configured routes
> 
> A full dump of current configuration

**Comment by Pols95** [comment]
Maybe the best way is to add a text-area to see and directly update the configuration?

**Comment by eolivelli** [comment]
IMO we must have the textarea
But we should also have some user friendly way to see what's really going on, that is the effective configuration that the system is using

**Comment by Pols95** [comment]
Disabled backends are ignored by endpoint mapper, so it's correct that are hidden in the UI (current behavior)
