### ISSUE TITLE
Security: authentication is not working

### ISSUE THREAD

**Issue by eolivelli** [diennea/carapaceproxy#106]

**Comment by Pols95** [comment]
In RuntimeServerConfiguration the dummy SimpleUserRealm is still used instead of FileUserRealm.

**Comment by eolivelli** [comment]
just put these lines in conf/server.properties
userrealm.class=org.carapaceproxy.user.FileUserRealm
userrealm.path=conf/user.properties

**Comment by hamadodene** [comment]
@eolivelli  
This configuration doesn't work for me.  
Is always loaded  the default class:  "INFO: userrealm.class=org.carapaceproxy.user.SimpleUserRealm".

**Comment by mino181295** [comment]
To me it don't make sense to have a FileUserRealm reading a conf from a File in a single machine if you are in cluster-database mode.

Proposals:
- Implement a LDAPUserRealm or a DatabaseUserRealm with a sessions and a Login page
- Load the file in a single machine inside the HerdDB database running when a service starts in cluster/database mode

**Comment by Pols95** [comment]
LDAP + HerdDB authentications are scheduled for milestone 2.0. For milestone 1.0 _Load the file in a single machine inside the HerdDB database running when a service starts in cluster/database mode_ should be enough IMHO.
