### ISSUE TITLE
Backends are not removed during reconfig

### ISSUE THREAD

**Issue by eolivelli** [diennea/carapaceproxy#11]
If I am removing a backend, from the current configuration, the change is not applied

**Comment by eolivelli** [comment]
Maybe I am wrong.
In the UI you can see only backend with activity.
It is okay that we don't drop the past.
Maybe this issue is only a duplicate of #10

**Comment by Pols95** [comment]
If you were using service without herddb (i.e. with PropertiesConfigurationStore) maybe it's a bug... Ii fact  dynamicConfigurationStore.commitConfiguration(newConfigurationStore); doesn't perform nothing rigtht now.
