### ISSUE TITLE
TLS : Possibility to Configure which TLS protocol use

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#160]
Possibility to configure which  TLS  protocol  use  (In particular, possibility to disable TLS 1.0 and 1.1).

**Comment by eolivelli** [comment]
Currently we let configure only sslciphers it should be quite simple to add this new configuration.

**Comment by eolivelli** [comment]
@aluccaroni can you tell us your preferred defaults ?

**Comment by aluccaroni** [comment]
@eolivelli default should be TLS1.2+ (so TLS1.2+TLS1.3)
