### ISSUE TITLE
Cluster mode:  Possibility to configure expectedreplicacount in server properties

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#166]
Carapace cluster starts  by creating a tablespace with expectedreplicacount:1.
It would better to be able to specify  in server.properties the number of expectedreplicacount:
example:
db.server.expectedreplicacount=2

**Comment by pv3nturi** [comment]
The option to use shoul be _**replication.factor**_ which defaults to 1.

**Comment by hamadodene** [comment]
I set replication.faction=2  but it doen't work

**Comment by hamadodene** [comment]
Maybe work only first start of the server

**Comment by pv3nturi** [comment]
It has to be set in **_static configuration_**
