### ISSUE TITLE
UI - support pagination configuration (10, 25, all)

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#182]
We currently have (10,25,50). 
I think is better have (10,25,all)

**Comment by aluccaroni** [comment]
"all" can be usefull to be able to export all the info of the Backend, for example

**Comment by pv3nturi** [comment]
DatatablaList.vue > set pageOptions: [
                    {"value": 10, "text": "10"},
                    {"value": 25, "text": "25"},
                    {"value": 0, "text": "all"}
                ],

**Comment by hamadodene** [comment]
I tested this change, but not working for me
