### ISSUE TITLE
UI > Show Certificate serial number

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#202]
Add a  new column in the  table **digital_certificates**  like serial_number and for every certificate save a serial number into this column. 

**NOTE:** It's important for every renew update the serial number because the sn is always different for each certificate.

**Comment by aluccaroni** [comment]
This is to track the actual let's encrypt ID (serial number) of the certificate in the case of bulk check/analysis (see, for example, the March 2020 mass cert revoke debacle: https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864)

**Comment by pv3nturi** [comment]
Certificate serial number has already stored on db but not showed on UI.
