### ISSUE TITLE
Access log rotation

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#214]
We need a way to tell carapace to create a new access.log/admin.access.log  file. There is no need for carapace to manage the rotation of the logs, but it is sufficient have possibility to send a signal to carapace so that can close old writer and open a new writer.

In my specif case i used logrotate for rotate my log.
This is an example of my configuration:

```
/my/install/path/access.log {
        daily
        missingok
        rotate 7
        compress
        delaycompress
        notifempty
        create 640 user user
        sharedscripts
        postrotate
                if [ -f /my/install/path/server.java.pid ]; then
                       //We need insert a signal here
                       //for example
                          kill -SIGNAL `cat /my/install/path/server.java.pid
                fi
        endscript
}


```

**Comment by aluccaroni** [comment]
@hamadodene i think you mean to use logrotate or similar, right? Please edit your request by adding exactly how you want this integration to work

**Comment by pv3nturi** [comment]
Something like this https://kostenko.org/blog/2019/08/java-catch-os-signals.html

**Comment by eolivelli** [comment]
it is better to have a builtin scheduler, without relying to external timers
