### ISSUE TITLE
Add content-encoding for text-based resources

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#240]
Text-based resources should be published with compression to minimize the total number of network bytes.

For more info https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

**Comment by pv3nturi** [comment]
Netty already supports it. We just need to adding the proper handler to the channel-to-client pipeline: https://stackoverflow.com/questions/8605519/how-to-use-netty-deflator-to-compress-the-response-sent-to-browser
