### ISSUE TITLE
Web page doesn't work in HTTPS during certificate renewal

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#251]
```
183855291-Feb 04, 2021 3:34:16 PM org.carapaceproxy.server.certificates.DynamicCertificatesManager getCertificateForDomain
2183855404:SEVERE: Dynamic certificate for domain *.mydomian is not available: CertificateData{domain=*.mydomian , state=ordering, available=false, manual=false}
```

While renewing a certificate, we noticed the web pages no longer respond correctly in https.
The correct behavior should be that until the certificate has been renewed, the latest available certificate is use.

**Comment by pv3nturi** [comment]
We need to drop the isAvailable flag.. Whether the certificate is expired we has to serve it as it is. Fallback certificate has to be served ONLY whether the certificate does not exists.

**Comment by hamadodene** [comment]
+1 for drop isAvaible flag
We should have something like:

- If the certificate is being renewed, serve the latest available certificate
- if the certificate has expired, serve it as it is
- if the certificate is not configured, fallback to the default certificate
- If the certificate is static and not working, fallback to the default certificate
- if the static certificate has expired, serve it as is
