### ISSUE TITLE
Handle Cache-control max-age

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#255]
We may receive a cache-Control header with a max-age = xxx. Based on the max-age we will have to delete the value from the cache when we exceed the max-age threshold.

For more info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by aluccaroni** [comment]
@hamadodene we do not strictly need to delete the value immediatly (it could be a costly operation for the memory), but we have to ensure that if a cache entry is marked as as expired (after the max-age is passed) and we receive a request for that resource that we download again the resource from the backend before serving it

We need to evaluate the best way to handle this case

**Comment by hamadodene** [comment]
@aluccaroni  Yes, i think that marked entry when is expired is a best solution in our case.
We already have a property "cache.maxSize" for flush cache when exided the set limit.
