### ISSUE TITLE
Manage cache mode in HTTPS requests

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#260]
If the call is in HTTPS it should not be cached by the intermediate (eg. the Reverse, such as Carapace), unless there is cache-control=public. If there is no Cache-Control = public it can be treated as a Cache-Control = private.

**Comment by aluccaroni** [comment]
NB: we don't need to change the content of the cache-control header...only evaluate if cache-control=public is present if the call is in https before caching
