### ISSUE TITLE
Manul certificate > Expiration date and serial number are not displayed

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#283]
When I upload a certificate via api, the expiration date and serial number are not displayed on the GUI.
If the certificate has expired it is still displayed as AVAILABLE.

**Comment by pv3nturi** [comment]
During manual certificate upload we need to extract the chain from keystore (maybe we'd better to manage  keystores password) and create a keystore with proper entry (like acme certificates keystore)
