### ISSUE TITLE
Set Carapace to use db configuration as default

### ISSUE THREAD

**Issue by pv3ntur1** [diennea/carapaceproxy#34]
Simply we need to set set in server.properties
config.type=database

And then in the HerdDBConfigurationStore constructor call __commitConfiguration__
right after __loadCurrentConfiguration__, in order to store the properties in the file server.properties (whether the db was empty) as fallback configuration.

**Comment by eolivelli** [comment]
@Pols95 I am not sure about the second part.
IMO no code change is needed.
The server will start with an empty database and it will remain in such state until the administration pushes a configuration from the API/UI

**Comment by Pols95** [comment]
Maybe the simplest solution is to use the db always and let the admin to specify an optional config file (like it's actually done) that will be load to the db.
