### ISSUE TITLE
Trust X-Forwarded-For header for some IPs

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#377]
At the moment, for each incoming request, in the presence of x-forwarded-for header, we remove it and replace it with the real ip from which the call came.

There are cases in the presence of a forward proxy or a CDN where we can trust the x-forwarded-for.

We must therefore have a property where it's possible to specify the list of IPs that we can trust.
If the request ip is included in this list, then the original x-forwarded-for header should not be removed. If no original x-forwarded-for header is present, we need to use the real ip.

**Comment by aluccaroni** [comment]
The IP allowed list must support full IP ranges-classes (best to use CIDR expressions)

**Comment by hamadodene** [comment]
I think we can use https://commons.apache.org/proper/commons-net/apidocs/org/apache/commons/net/util/SubnetUtils.html

**Comment by aluccaroni** [comment]
Linked to https://github.com/diennea/carapaceproxy/issues/383
