### ISSUE TITLE
Possibility to generate a certificate that covers multiple domains

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#380]
In some cases it may be necessary to generate a certificate that covers several domains such as:
**example.com www.example.com**
or even a certificate covering wildcard and domain itself like: **example.com * .example.com**

Another example:
- www.example.com www.example.it

It would be useful to enable this possibility.

**Comment by aluccaroni** [comment]
@hamadodene we need to support the Subject Alternative Name extensions. I suggest to add a new configuration line, something like:
certificate.ID.hostname=example.com
certificate.ID.san=www.example.com,www2.example.com
certificate.ID.mode=acme

**Comment by hamadodene** [comment]
I agree with @aluccaroni 
There would be the case of multiple wildcard certificates.
In the Letsencrypt forum they say it's possible. I would first evaluate how complex it is to do it with acme4j (See https://community.letsencrypt.org/t/multi-domain-wildcard-certificate/113577/9). If too complex we can avoid support with multiple wildcard certificates. 

By multiple wildcard certificates I mean something like:

certificate.ID.hostname=*.example.com
certificate.ID.san=*.example2.com 
certificate.ID.mode=acme
