### ISSUE TITLE
ConnectionManagerImpl#getConnection() improve capacity of connections pool

### ISSUE THREAD

**Issue by pv3ntur1** [diennea/carapaceproxy#40]
@hamadodene found out that caracape breaks when over 50k connections are made:
`INFO: RequestHandler{id=1202587, connectionToEndpoint=null, connectionToClient=ClientConnectionHandler{1202355,ka=null}, last 1551788163386} error on endpoint MapResult{host=localhost, port=8083, action=PROXY, errorcode=0, resource=null}: org.carapaceproxy.client.EndpointNotAvailableException: Too many connections to EndpointKey{host=localhost, port=8083} and/or cannot create a new connection`

**Comment by eolivelli** [comment]
default value of connectionsmanager.maxconnectionsperendpoint is 10
maybe @hamadodene  you should try with a bigger value
