### ISSUE TITLE
Dynamic certificate > Domain unreachable if no SAN is specified

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#401]
Doing some checks I realized that if no SAN is specified, the certificate creation fails with DOMAIN UNREACHBLE.
From code I noticed that subjectAltNames is a Set<String> and when we go to create the collection with all the certificates we verify that this is not null.

```
Class: DynamicCertificatesManager

    final var allNamesReachable = cert.getNames().stream().allMatch(name -> {
        try {
            return CertificatesUtils.isWildcard(name) || checkDomain(name);
        } catch (AcmeException e) {
            return false;
        }
    });
```
```
Class  CertificateData:

    public Collection<String> getNames() {
        return new ArrayList<>() {{
            add(domain);
            if (subjectAltNames != null) {
                addAll(subjectAltNames);
            }
        }};
    }
```

The problem is at that point the Set seems to be initialized, so if no SAN is present the set is empty and not NULL

**Comment by NiccoMlt** [comment]
The problem seems to be in `org.carapaceproxy.api.CertificatesResource#uploadCertificate`, where it defaults the parameter `subjectAltNames` to `""`, but then at line 330 it doesn't treat it as an empty value, but as a name
