### ISSUE TITLE
Certificates > admin ui certificates warning

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#402]
On the certificates page, we currently only provide a warning for expired certificates.

It would be interesting to have a signal for certificates in Failed state and in unreacheble state.

This would allow user to have a more precise and immediate view of the status of certificates.

A possible solution would be to provide a form or even two buttons with something like:
Failed certificates: 6
Unreachable certificates: 3
You could also use something like the expired certificate warning.
![image](https://user-images.githubusercontent.com/43852233/213181402-5d18c6c9-db29-42ed-a673-d84cdef6400b.png)

Maybe we can make them clickable to view the list of certificates in that specific state.

**Comment by NiccoMlt** [comment]
Makes sense. I think we should discuss the structure of the page to avoid cluttering it too much
