### ISSUE TITLE
route match show  regex with back-slash  configuration 

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#43]
example: 
` "test\.test\.test\/test/.*" `
if i set this string,  after reload  the regex change in --> test.test.test/test/.* 
if i save my current configuration carapace override  `"test\.test\.test\/test/.*"` with  test.test.test/test/.* .

**Comment by Pols95** [comment]
It's a db saving bug... Regex patterns are saved as string with "\" yet processed
