### ISSUE TITLE
Return 503 Service unavailable when all backend is unavailable

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#436]
Currently when all backends are down we return 500 internal server error by default.
But I think we will have to return service unavailable.
500 internal error should be the errors in cases of problems on the Carapace side, such as:
- no action configured
- no backend configured
that is, errors internal to Carapace that are not attributable to problems on the backend side.

**Comment by NiccoMlt** [comment]
Yes, I agree with your assessment. 
Returning a [500 Internal Server Error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500)typically indicates an issue with the server itself, not necessarily with the upstream services or backends. 
When all backend services are down, it's more appropriate to return a [503 Service Unavailable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503).
