### ISSUE TITLE
Upgrade to java 21

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#438]

**Comment by NiccoMlt** [comment]
We already can _run_ on Java **21** (https://github.com/diennea/carapaceproxy/issues/470), I think we should jump directly from Java 17 to Java 21 as the compile version.

What do you think @hamadodene? If you agree, please update the issue title; if you don't let's discuss it 😄, maybe I'm missing some compatibility issue

**Comment by hamadodene** [comment]
We can update the title and test Carapace on java 21 locally and the if there's any issue we can creare a dedicated one

**Comment by NiccoMlt** [comment]
Makes sense

Maybe we could just bump the Java version in the POM and keep a look on potential problems

**Comment by hamadodene** [comment]
@NiccoMlt Yes ...Feel free to send a PR...We also need to run the tests in JAVA 21.
