### ISSUE TITLE
Option to add a debug header to see which route/action/director/backend were selected (X-Proxy-Path header)

### ISSUE THREAD

**Issue by eolivelli** [diennea/carapaceproxy#44]
If would be useful an option (dynamic) (or simply a "filter") which shows which tuple route/action/director/backend have been chooser in order to serve the request.

This way it will be simpler to debug the "final" configuration

**Comment by Pols95** [comment]
This should be available for all the requests (i.e. a global configuration/option) or just for specific actions?
