### ISSUE TITLE
Ability to force https connections on given URIs: error and/or redirect

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#48]
Is possible to force connection from http to https ?
That is, when the listener receives an HTTP connection, it can force the connection from HTTP to https only when necessary.

**Comment by eolivelli** [comment]
For every request or only for some given path?

**Comment by hamadodene** [comment]
@eolivelli 
only for some given path

**Comment by hamadodene** [comment]
@eolivelli

**Comment by eolivelli** [comment]
let's introduce a new "system" action "force-https", and for the selection of the route we will use #61

**Comment by eolivelli** [comment]
or a new more generic action 'redirect' with a special "Location" "self+https

```
action.1.id=dddd
action.1.type=redirect
action.1.location=/relative/location


action.2.id=dddd
action.2.type=redirect
action.2.location=http://server/absolute/location

action.3.id=dddd
action.3.type=redirect
action.4.location=same
```-over-https

**Comment by Pols95** [comment]
My proposal:

action.1.id=dddd
action.1.type=redirect
action.1.redirect.location=/relative/location

action.2.id=dddd
action.2.type=redirect
action.2.redirect.location=http://server/absolute/location

action.3.id=dddd
action.3.type=redirect
action3.redirect.forcehttps=true

**Comment by eolivelli** [comment]
Why '.redirect.' ?
