### ISSUE TITLE
Forwarded IF_TRUSTED trustedips> Add default identifier if not specified by the user

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#492]
While trying to configure forwarding on the listener side in IF_TRUSTED mode, with trusted IPs set, for example, as:
listener.1.trustedips=127.0.0.1, I encounter the following error:
```

Sep 09, 2024 5:57:50 PM reactor.util.Loggers$Slf4JLogger warn
WARNING: [b6d39a29, L:/10.208.1.36:4089 - R:/77.238.21.10:22647] Decoding failed: REQUEST(decodeResult: failure(java.lang.IllegalArgumentException: Could not parse [127.0.0.1]), version: HTTP/1.1)
GET / HTTP/1.1
Host: <filtered>
Connection: <filtered>
Pragma: <filtered>
Cache-Control: <filtered>
sec-ch-ua: <filtered>
sec-ch-ua-mobile: <filtered>
sec-ch-ua-platform: <filtered>
Upgrade-Insecure-Requests: <filtered>
User-Agent: <filtered>
Accept: <filtered>
Sec-Fetch-Site: <filtered>
Sec-Fetch-Mode: <filtered>
Sec-Fetch-User: <filtered>
Sec-Fetch-Dest: <filtered>
Accept-Encoding: <filtered>
Accept-Language: <filtered>
Cookie: <filtered>
x-forwarded-for: <filtered>
 
```

The library we are using likely raises this error due to the missing identifier. Therefore, the CIDR notation should always be specified, e.g., listener.1.trustedips=127.0.0.1/32.

We could consider adding a default identifier if the user does not specify one.
In my opinion, the default could be to simply add `/32 `if not otherwise specified

**Comment by NiccoMlt** [comment]
Follow-up of #477
