### ISSUE TITLE
Refactor metrics to use pure Prometheus.io API and labels

### ISSUE THREAD

**Issue by eolivelli** [diennea/carapaceproxy#73]
We are using BookKeeper StatsLogger but this API does not support 'labels'
we should move to the usage of Prometheus Labels.

**Comment by eolivelli** [comment]
@dmercuriali are you interested in providing a fix ?

**Comment by dmercuriali** [comment]
Created a PR https://github.com/diennea/carapaceproxy/pull/92
Refactored metrics:
backends_pending_requests GAUGE
backends_stuck_requests_total COUNTER
backends_connection_time_ns SUMMARY [host (host_port), result(success/failure)], quantiles 0.5 0.9 0.99
backends_open_connections GAUGE [host (host_port)]
backends_active_connections GAUGE [host (host_port)]
backends_sent_requests_total COUNTER [host (host_port)]

listeners_requests_total COUNTER [listener (host_port)]
listeners_running_requests GAUGE
listeners_user_requests_total COUNTER [userId]

clients_current_connected GAUGE

health_backend_status GAUGE [host (host_port)] - 0/1

cache_hits_total COUNTER
cache_misses_total COUNTER
cache_payload_memory_usage_bytes GAUGE [area (direct/heap)]
cache_total_memory_usage_bytes GAUGE
cache_non_cachable_requests_total COUNTER
