### ISSUE TITLE
Let's Encrypt cetificates:  backward compatibility with default intermediate certificate 

### ISSUE THREAD

**Issue by pv3nturi** [diennea/carapaceproxy#74]
Due to https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html
from July certificates issued by let'encrypt won't be cross-signed by IdenTrust anymore. This means that oldest clients will not trust LE certificates.
We need a way to mantain IdenTrust certificate as default intermediate one.

More info:
https://letsencrypt.org/certificates/

See also:
https://community.letsencrypt.org/t/how-to-request-identrust-intermediate-ca/91323
https://github.com/certbot/certbot/issues/6971

**Comment by davidegiunchidiennea** [comment]
[https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html](https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html)

> Due to concerns about insufficient ISRG root propagation on Android devices we have decided to move the date on which we will start serving a chain to our own root from July 8, 2019, to July 8, 2020.

I think that i can close the issue, the next year we will re-open it

**Comment by hamadodene** [comment]
We can close this issue...In Carapace we don't use idenTrust Certificate but we use LE standard chain.
