### ISSUE TITLE
Certificates: DB management for Static Certificates

### ISSUE THREAD

**Issue by Pols95** [diennea/carapaceproxy#76]
We need to change the way we manage static certificates. They have to be manage as dynamic (cert file should be store in db) but without auto renew (admin will do explicitly)

**Comment by Pols95** [comment]
We need to change the way we manage static certificates. They have to be manage as dynamic (cert file should be store in db) but without auto renew (admin will do explicitly)

**Comment by aluccaroni** [comment]
For integration with external certs provided we need a command to upload a updated cert to DB (or we need to add a "location" information inside the DB so Carapace can load the cert from that location) and we need to add a command line command that reload the cert in question.

It's preferred to have a command that can reload a specific certs and/or all the certs (carapace-reload-cert * | carapce-reload-cert pippo.com /opt/mn/pippo.com.2020.crt)

**Comment by aluccaroni** [comment]
@eolivelli this needs to be done soon (0.1.0/0.2.0)
